HR.Web/Models/Company.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string RegNo { get; set; }
        public string CompanyLogo { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> InCorporationDate { get; set; }
    }
}

HR.Web/Controllers/AdministrationController.cs
using HR.Web.Models;
using HR.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace HR.Web.Controllers
{
    [SessionFilter]
    public class AdministrationController : Controller
    {
        // GET: Administration
        [HttpGet]
        public ActionResult Company(int companyId = 0)
        {
            CompanyVm companyvm = new CompanyVm();
            using (HrDataContext dbContext = new HrDataContext())
            {
                Company company = dbContext.Companies.Where(x => x.CompanyId == companyId).FirstOrDefault();

                if (company != null)
                {
                    companyvm.company = new CompanyVmObj();
                    companyvm.company.CompanyCode = company.CompanyCode;
                    companyvm.company.CompanyId = company.CompanyId;
                    companyvm.company.CompanyName = company.CompanyName;
                    companyvm.company.CreatedBy = company.CreatedBy;
                    companyvm.company.CreatedOn = company.CreatedOn;
                    companyvm.company.InCorporationDate = company.InCorporationDate;
                    companyvm.company.IsActive = company.IsActive;
                    companyvm.company.ModifiedBy = company.ModifiedBy;
                    companyvm.company.ModifiedOn = company.ModifiedOn;
                    companyvm.company.RegNo = company.RegNo;


                }
                companyvm.companyAddress = new AddressVm();

                Address address = dbContext.Addresses.Where(x => x.LinkID == companyId).FirstOrDefault();
                if (address != null)
                {
                    companyvm.companyAddress.Address1 = address.Address1;
                    companyvm.companyAddress.Address2 = address.Address2;
                    companyvm.companyAddress.AddressId = address.AddressId;
                    companyvm.companyAddress.AddressType = address.AddressType;
                    companyvm.companyAddress.CityName = address.CityName;
                    companyvm.companyAddress.Contact = address.Contact;
                    companyvm.companyAddress.CountryCode = address.CountryCode;
                    companyvm.companyAddress.CreatedBy = address.CreatedBy;
                    companyvm.companyAddress.CreatedOn = address.CreatedOn;
                    companyvm.companyAddress.Email = address.Email;
                    companyvm.companyAddress.FaxNo = address.FaxNo;
                    companyvm.companyAddress.IsActive = address.IsActive;
                    companyvm.companyAddress.LinkID = address.LinkID;
                    companyvm.companyAddress.MobileNo = address.MobileNo;
                    companyvm.companyAddress.ModifiedBy = address.ModifiedBy;
                    companyvm.companyAddress.ModifiedOn = address.ModifiedOn;
                    companyvm.companyAddress.SeqNo = address.SeqNo;
                    companyvm.companyAddress.StateName = address.StateName;
                    companyvm.companyAddress.TelNo = address.TelNo;
                    companyvm.companyAddress.WebSite = address.WebSite;
                    companyvm.companyAddress.ZipCode = address.ZipCode;
                }

                var result = dbContext.Companies.GroupJoin(dbContext.Branches,
                    a => a.CompanyId, b => b.CompanyId,
                            (a, b) => new { A = a, B = b }).ToList();
                companyvm.companyTreeVm = new List<companyTreeVm>();
                companyTreeVm companyTreeVm = new companyTreeVm();
                foreach (var item in result)
                {
                    companyTreeVm.href = item.A.CompanyId.ToString();
                    companyTreeVm.text = item.A.CompanyName;
                    companyTreeVm.nodes = new List<branchTreeVm>();
                    foreach (var subitem in item.B)
                    {
                        branchTreeVm branchVM = new branchTreeVm()
                        {
                            href = subitem.BranchID.ToString(),
                            text = subitem.BranchName,
                        };
                        companyTreeVm.nodes.Add(branchVM);
                    }
                }
                companyvm.companyTreeVm.Add(companyTreeVm);
            }

            return View(companyvm);
        }
        [HttpPost]
        public ActionResult Company(CompanyVm companyVM, AddressVm addressVm)
        {
            try
            {
                using (HrDataContext dbContext = new HrDataContext())
                {
                    if (companyVM.company.CompanyId == 0)
                    {

                        Company company = new Company();

                        company.CompanyCode = companyVM.company.CompanyCode;
                        company.CompanyName = companyVM.company.CompanyName;
                        company.CreatedBy = "Admin";
                        company.CreatedOn = DateTime.Now;
                        company.InCorporationDate = companyVM.company.InCorporationDate;
                        company.IsActive = true;

                        if (companyVM.company.Logo != null && companyVM.company.Logo.ContentLength > 0)
                        {
                            company.CompanyLogo = companyVM.company.Logo.FileName;
                            string path = Server.MapPath("~/Uploads/");
                            if (!Directory.Exists(path))
                            {
                                Directory.CreateDirectory(path);
                            }
                            companyVM.company.Logo.SaveAs(path + company.CompanyLogo);
                        }

                        company.RegNo = companyVM.company.RegNo;
                        company.ModifiedBy = "Admin";
                        company.ModifiedOn = DateTime.Now;


                        Address companyAddress = new Address()
                        {
                            Address1 = addressVm.Address1,
                            Address2 = addressVm.Address2,

                            AddressType = "Company",
                            CityName = addressVm.CityName,
                            Contact = addressVm.Contact,
                            CountryCode = addressVm.CountryCode,
                            LinkID = company.CompanyId,
                            CreatedBy = "Admin",
                            CreatedOn = DateTime.Now,
                            Email = addressVm.Email,
                            FaxNo = addressVm.FaxNo,
                            MobileNo = addressVm.MobileNo,
                            IsActive = true,
                            ModifiedBy = "Admin",
                            ModifiedOn = DateTime.Now,
                            SeqNo = addressVm.SeqNo,
                            StateName = addressVm.StateName,
                            TelNo = addressVm.TelNo,
                            WebSite = addressVm.WebSite,
                            ZipCode = addressVm.ZipCode,
                        };

                        dbContext.Companies.Add(company);
                        dbContext.Addresses.Add(companyAddress);
                    }
                    else
                    {

                        Company company = dbContext.Companies.
                            Where(x => x.CompanyId == companyVM.company.CompanyId).FirstOrDefault();

                        company.CompanyCode = companyVM.company.CompanyCode;
                        company.CompanyName = companyVM.company.CompanyName;
                        company.CreatedBy = "Admin";
                        company.CreatedOn = DateTime.Now;
                        company.InCorporationDate = companyVM.company.InCorporationDate;
                        company.IsActive = true;

                        if (companyVM.company.Logo != null && companyVM.company.Logo.ContentLength > 0)
                        {
                            company.CompanyLogo = companyVM.company.Logo.FileName;
                            string path = Server.MapPath("~/Uploads/");
                            if (!Directory.Exists(path))
                            {
                                Directory.CreateDirectory(path);
                            }
                            companyVM.company.Logo.SaveAs(path + company.CompanyLogo);
                        }

                        company.RegNo = companyVM.company.RegNo;
                        company.ModifiedBy = "Admin";
                        company.ModifiedOn = DateTime.Now;

                        Address branchAddress = dbContext.Addresses.
                            Where(x => x.LinkID == companyVM.company.CompanyId).FirstOrDefault();

                        branchAddress.Address1 = addressVm.Address1;
                        branchAddress.Address2 = addressVm.Address2;

                        branchAddress.AddressType = "Company";
                        branchAddress.CityName = addressVm.CityName;
                        branchAddress.Contact = addressVm.Contact;
                        branchAddress.CountryCode = addressVm.CountryCode;
                        branchAddress.LinkID = company.CompanyId;
                        branchAddress.CreatedBy = "Admin";
                        branchAddress.CreatedOn = DateTime.Now;
                        branchAddress.Email = addressVm.Email;
                        branchAddress.FaxNo = addressVm.FaxNo;
                        branchAddress.MobileNo = addressVm.MobileNo;
                        branchAddress.IsActive = true;
                        branchAddress.ModifiedBy = "Admin";
                        branchAddress.ModifiedOn = DateTime.Now;
                        branchAddress.SeqNo = addressVm.SeqNo;
                        branchAddress.StateName = addressVm.StateName;

HR.Web/Views/Administration/AddBranch.cshtml
@model HR.Web.ViewModels.BranchVm
@section Styles{
    <style type="text/css">
        .icheckbox_flat {
            margin-top: -23px;
        }
    </style>
}
@using (Html.BeginForm("AddBranch", "Administration", FormMethod.Post, new
{ id = "frmBranch", name = "frmBranch", enctype = "multipart/form-data" })) { 
<div class="page">
    <div class="row">
        <div class="col-md-3">
            <div class="row">
                @{Html.RenderPartial("_TreeView", Model.companyTreeVm); }
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default panel-hovered panel-stacked mb10">
                        <div class="panel-heading">Branch</div>

                        <div class="panel-body">
                            <div class="row css5">
                                @Html.HiddenFor(x => x.branch.BranchID)
                                <div class="form-group">
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">Branch Code</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.BranchCode, new { @class = "form-control" })
                                    </div>
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">IsActive</span>
                                    </label>
                                    <div class="col-md-4">
                                        <div style="margin-top:20px;">
                                            @Html.CheckBoxFor(x => x.branch.IsActive)
                                        </div>
                                        
                                    </div>
                                    @*<div class="ui-toggle ui-toggle-sm ui-toggle-primary mb10">
                                        <label class="ui-toggle-inline">
                                            <label class="ui-toggle-inline">
                                                <input id="IsActive" name="IsActive.Value" type="checkbox">
                                                <span></span>
                                            </label>
                                        </label>
                                    </div>*@
                                </div>
                            </div>
                            <div class="row css5">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">Branch Name</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.BranchName, new { @class = "form-control" })
                                    </div>
                                    <label class="col-md-2 control-label">
                                        <span class="pull-right">Registration No</span>
                                    </label>
                                    <div class="col-md-4">
                                        @Html.TextBoxFor(x => x.branch.RegNo, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @{Html.RenderPartial("_Address", Model.address);}
                </div>
            </div>
        </div>
    </div>
    

    

    <div class="row">
        <div class="col-md-12">
            <div>
                <button class="btn btn-primary btn-sm" type="button" onclick="SaveBranch()"><i class="fa fa-floppy-o" aria-hidden="true"></i>Save</button>
            </div>
        </div>
    </div>
</div>
}

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $('#li_Admin').addClass('open');
            $('#li_company').addClass('active');
        });
            $('#frmBranch').validate({
                rules: {
                    'branch.BranchCode': {
                        required:true
                    },
                    'branch.BranchName': {
                        required: true
                    },
                    'branch.RegNo': {
                        required: true
                    },
                    //'company.InCorporationDate': {
                    //    required: true
                    //},
                    'Address1': {
                        required: true
                    },
                    'CityName': {
                        required: true
                    },
                    'StateName': {
                        required: true
                    },
                    'CountryCode': {
                        required: true
                    },
                    'TelNo': {
                        required: true
                    },
                    'FaxNo': {
                        required: true
                    },
                    'MobileNo': {
                        required: true
                    },
                    'Contact': {
                        required: true
                    },
                    'Email': {
                        'email':true,
                        required: true
                    },
                }
            });
       
        function SaveBranch()
        {
            if ($('#frmBranch').valid()) {
                $('#frmBranch').submit()
            }

        }
    </script>
}

HR.Web/Views/Administration/Company.cshtml
@model HR.Web.ViewModels.CompanyVm

@section Styles{
    <style type="text/css">
        .icheckbox_flat {
            margin-top: -23px;
        }
    </style>
}
@using (Html.BeginForm("Company", "Administration", FormMethod.Post, new
{ id = "frmCompany", name = "frmCompany", enctype = "multipart/form-data" }))
{
    <div class="page">
        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    @{Html.RenderPartial("_TreeView", Model.companyTreeVm); }
                </div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default panel-hovered panel-stacked mb10">
                            <div class="panel-heading">Company</div>
                            @Html.HiddenFor(x => x.company.CompanyId)
                            <div class="panel-body">
                                <div class="row css5">

                                    <div class="form-group">
                                        <label class="col-md-2 control-label">
                                            <span class="pull-right">CompanyCode</span>
                                        </label>
                                        <div class="col-md-4">
                                            @Html.TextBoxFor(x => x.company.CompanyCode, new { @class = "form-control" })
                                        </div>
                                        <label class="col-md-2 control-label">
                                            <span class="pull-right">IsActive</span>
                                        </label>
                                        <div class="col-md-4">                                            
                                            <div style="margin-top:20px;">
                                                @Html.CheckBoxFor(x => x.company.IsActive)
                                            </div>
                                        </div>
                                        @*<div class="ui-toggle ui-toggle-sm ui-toggle-primary mb10">
                                            <label class="ui-toggle-inline">
                                                <label class="ui-toggle-inline">
                                                    <input id="IsActive" name="IsActive.Value" type="checkbox">
                                                   
                                                    <span></span>
                                                </label>
                                            </label>
                                        </div>*@
                                    </div>
                                </div>
                                <div class="row css5">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">
                                            <span class="pull-right">Company Name</span>
                                        </label>
                                        <div class="col-md-4">
                                            @Html.TextBoxFor(x => x.company.CompanyName, new { @class = "form-control" })
                                        </div>
                                        <label class="col-md-2 control-label">
                                            <span class="pull-right">Registration No</span>
                                        </label>
                                        <div class="col-md-4">
                                            @Html.TextBoxFor(x => x.company.RegNo, new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row css5">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">
                                            <span class="pull-right">InCorporate Date</span>
                                        </label>
                                        <div class="col-md-4">
                                            <div class="input-group date dtCss" id="CorporationDate">
                                                @Html.TextBoxFor(x => x.company.InCorporationDate, new { @class = "form-control" })
                                                <span class="input-group-addon">
                                                    <i class="ion ion-calendar"></i>
                                                </span>
                                            </div>
                                        </div>
                                        <label class="col-md-2 control-label">
                                            <span class="pull-right">Tax ID</span>
                                        </label>
                                        <div class="col-md-4">
                                            @*@Html.TextBoxFor(x => x.Gst, new { @class = "form-control" })*@
                                        </div>
                                    </div>
                                </div>
                                <div class="row css5">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">
                                            <span class="pull-right">Logo</span>
                                        </label>
                                        <div class="col-md-4">
                                            @Html.TextBoxFor(x => x.company.Logo, new { type = "file" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        @{Html.RenderPartial("_Address", Model.companyAddress); }
                    </div>                    
                </div>
            </div>
        </div>
        
        

        

        <div class="row">
            <div class="col-md-12">
                <div>
                    <button class="btn btn-primary btn-sm" type="button" onclick="SaveCompany()"><i class="fa fa-floppy-o" aria-hidden="true"></i>Save</button>
                </div>
            </div>
        </div>
    </div>
            }

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $('#li_Admin').addClass('open');
            $('#li_company').addClass('active');
            /*Tree View Starts*/


            /*Tree View Ends*/


            $('.dtCss').datetimepicker({
                icons: {
                    time: 'fa fa-clock-o',
                    date: 'fa fa-calendar',
                    up: 'fa fa-arrow-up',
                    down: 'fa fa-arrow-down',
                    previous: 'fa fa-arrow-left',
                    next: 'fa fa-arrow-right'
                },
                format: 'DD/MM/YYYY'
            });

            $('#frmCompany').validate({
                rules: {
                    'company.CompanyCode': {
                        required: true,
                        maxlength:20
                    },
                    'company.CompanyName': {
                        required: true,
                        maxlength:200
                    },
                    'company.RegNo': {
                        required: true
                    },
                    //'company.InCorporationDate': {
                    //    required: true
                    //},
                    'Address1': {
                        required: true,
                        maxlength:200
                    },
                    'CityName': {
                        required: true
                    },
                    'StateName': {
                        required: true
                    },
                    'CountryCode': {
                        required: true
                    },
                    'TelNo': {
                        required: true
                    },
                    'FaxNo': {
                        required: true
                    },
                    'MobileNo': {
                        required: true
                    },
                    'Contact': {
                        required: true
                    },
                    'Email': {
                        'email': true,
                        required: true
                    },
                }
            });
        })
        function SaveCompany() {
            if ($('#frmCompany').valid()) {
                $('#frmCompany').submit()
            }

        }
    </script>
}