HR.Web/Models/EmployeeLeaveList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveList
    {
        public int EmployeeLeaveID { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public int BranchId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<decimal> Days { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int ManagerId { get; set; }
        public Nullable<decimal> LossOfPayDays { get; set; }
        public bool IsLossOfPay { get; set; }
    }
}

HR.Web/Models/HolidayList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayList
    {
        public int HolidayId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int BranchID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int CountryId { get; set; }
    }
}

HR.Web/Models/Leave.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LeaveId { get; set; }
        public Nullable<int> PaidLeavesPerYear { get; set; }
        public Nullable<decimal> PaidLeavesPerMonth { get; set; }
        public bool IsPaidLeaveCarryForward { get; set; }
        public Nullable<decimal> CarryForwardPerYear { get; set; }
        public Nullable<int> SickLeavesPerYear { get; set; }
        public Nullable<decimal> SickLeavesPerMonth { get; set; }
        public bool IsSickLeaveCarryForward { get; set; }
        public Nullable<decimal> CarryForwardSickLeaves { get; set; }
        public Nullable<int> CasualLeavesPerYear { get; set; }
        public Nullable<decimal> CasualLeavesPerMonth { get; set; }
        public bool IsCasualLeaveCarryForward { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<decimal> CarryForwardCasualLeave { get; set; }
    }
}

HR.Web/Controllers/LeaveController.cs
using HR.Web.Helpers;
using HR.Web.Models;
using HR.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace HR.Web.Controllers
{
    [SessionFilter]
    public class LeaveController : BaseController
    {


        // GET: Leave
        #region HolidayList
        public ActionResult HolidayList()
        {
            ViewData["RoleCode"] = ROLECODE;
            using (HrDataContext dbContext = new HrDataContext())
            {
                var obj = dbContext.HolidayLists.ToList();
                List<calendarVM> holidayList = new List<calendarVM>();
                foreach (HolidayList item in obj)
                {
                    calendarVM list = new calendarVM();
                    list.title = item.Description;
                    list.date = item.Date;
                    var strHref = "";
                    if (ROLECODE == UTILITY.ROLE_EMPLOYEE)
                    {
                        strHref = "#";
                    }
                    else
                        strHref = "~/Leave/AddHoliday" + "?HolidayId=" + item.HolidayId;

                    var context = new HttpContextWrapper(System.Web.HttpContext.Current);
                    string hrefUrl = UrlHelper.GenerateContentUrl(strHref, context);
                    list.url = hrefUrl;
                    holidayList.Add(list);
                }
                holidayVm holidayVm = new holidayVm()
                {
                    calendarVM = holidayList,
                    HolidayList = new HolidayList()
                };
                return View("HolidayList", holidayVm);
            }

        }

        public ActionResult AddHoliday(int HolidayId)
        {
            ViewData["RoleCode"] = ROLECODE;
            using (HrDataContext dbContext = new HrDataContext())
            {
                var obj = dbContext.HolidayLists.ToList();
                holidayVm holidayVm = new holidayVm();
                List<calendarVM> holidayList = new List<calendarVM>();
                foreach (HolidayList item in obj)
                {
                    calendarVM list = new calendarVM();
                    list.title = item.Description;
                    list.date = item.Date;

                    var strHref = "~/Leave/AddHoliday" + "?HolidayId=" + item.HolidayId;

                    var context = new HttpContextWrapper(System.Web.HttpContext.Current);
                    string hrefUrl = UrlHelper.GenerateContentUrl(strHref, context);
                    list.url = hrefUrl;
                    holidayList.Add(list);



                    holidayVm.calendarVM = holidayList;
                    holidayVm.HolidayList = dbContext.HolidayLists.Where(x => x.HolidayId == HolidayId).FirstOrDefault();
                }
                return View("HolidayList", holidayVm);
            }

        }

        public PartialViewResult GetHolidayList(int holidayId)
        {
            if (holidayId != -1)
            {
                using (var dbntx = new HrDataContext())
                {
                    var holidaylist = dbntx.HolidayLists.Where(x => x.HolidayId == holidayId).FirstOrDefault();
                    return PartialView(holidaylist);
                }
            }
            else
            {
                var dt = DateTime.Now;
                return PartialView(new HolidayList
                {
                    Date = DateTime.Now,
                    HolidayId = -1
                });
            }

        }

        public ActionResult SaveHoliday(HolidayList holidaylist)
        {

            if (holidaylist.HolidayId != -1)
            {
                using (var dbnctx = new HrDataContext())
                {
                    var _holidaylistObj = dbnctx.HolidayLists.Where(x => x.HolidayId == holidaylist.HolidayId).FirstOrDefault();

                    //_holidaylistObj.HolidayId = holidaylist.HolidayId;
                    _holidaylistObj.Date = holidaylist.Date;
                    _holidaylistObj.Description = holidaylist.Description;
                    _holidaylistObj.CountryId = holidaylist.CountryId;
                    _holidaylistObj.ModifiedBy = USERID;
                    _holidaylistObj.ModifiedOn = UTILITY.SINGAPORETIME;

                    dbnctx.SaveChanges();
                }
            }
            else
            {

                using (var dbntcx = new HrDataContext())
                {
                    var holidaylistobj = new HolidayList
                    {
                        BranchID = BRANCHID,
                        HolidayId = holidaylist.HolidayId,
                        Date = holidaylist.Date,
                        Description = holidaylist.Description,
                        CountryId = holidaylist.CountryId,
                        CreatedOn = UTILITY.SINGAPORETIME,
                        CreatedBy = USERID,
                        ModifiedOn = UTILITY.SINGAPORETIME,
                        ModifiedBy = USERID
                    };
                    dbntcx.HolidayLists.Add(holidaylistobj);
                    dbntcx.SaveChanges();
                }
            }

            return RedirectToAction("HolidayList");

        }





        #endregion


        public ViewResult AppliedLeaveList()
        {
            string viewName = string.Empty;
            using (var dbCntx = new HrDataContext())
            {
                var empLeaveList = dbCntx.Branches.GroupJoin(dbCntx.EmployeeLeaveLists.
                    empLeaveListWhere(ROLECODE, BRANCHID, EMPLOYEEID, ref viewName),
                        a => a.BranchID, b => b.BranchId, (a, b) => new { A = a, B = b.AsEnumerable() })

                        .Select(x => new AppliedLeaveListVm
                        {
                            BranchID = x.A.BranchID,
                            BranchName = x.A.BranchName,
                            employeeLeaveList = x.B.Select(y => new EmpLeaveListVm
                            {
                                EmployeeName = dbCntx.EmployeeHeaders.Where(m => m.EmployeeId == y.EmployeeId).Select(z => new
                                {
                                    EmployeeFullName = z.FirstName + " " + z.LastName,

                                }).FirstOrDefault().EmployeeFullName,
                                EmployeeId = y.EmployeeId,
                                FromDate = y.FromDate,
                                ToDate = y.ToDate,
                                Status = y.Status
                            })
                        }).ToList();

                return View(viewName, empLeaveList);
            }
        }

        public JsonResult GetBranchLeaveData(int branchId, int pageNo)
        {

            int offSet = 10;
            int skipRows = (pageNo - 1) * offSet;
            using (var dbCntx = new HrDataContext())
            {
                var Query = dbCntx.EmployeeHeaders
                                        .Join(dbCntx.EmployeeLeaveLists,
                                        a => a.BranchId, b => b.BranchId, (a, b) => new { A = a, B = b })
                                        .Where(x => x.A.BranchId == branchId);

                var empLeaveList = Query
                                        .OrderBy(x => x.A.EmployeeId)
                                        .Skip(skipRows)
                                        .Take(offSet)
                                        .Select(x => new EmpLeaveListVm
                                        {
                                            EmployeeName = x.A.FirstName + " " + x.A.LastName,
                                            EmployeeId = x.B.EmployeeId,
                                            FromDate = x.B.FromDate,
                                            ToDate = x.B.ToDate
                                        }).ToList();

                return Json(new
                {
                    empLeaveList = empLeaveList,
                    pagerLength = Query.Count()
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EmployeeRequestFrom()
        {


            return View(new EmployeeLeaveList
            {
                // FromDate = DateTime.Now,
                //  ToDate = DateTime.Now
            });
        }

        [HttpPost]
        public ActionResult SaveEmployeeLeaveForm(EmployeeLeaveList EmployeeLeaveList)
        {
            bool ishalfday = false;
            if (Request.Form["isChecked"] != null && Request.Form["isChecked"] != "")
            {
                ishalfday = Request.Form["isChecked"] == "on";
                if (ishalfday)
                    EmployeeLeaveList.Days = 0.5m;
            }
            using (var dbCntx = new HrDataContext())
            {
                EmployeeLeaveList obj = new EmployeeLeaveList();

                var isPreviousLeaveExists = dbCntx.EmployeeLeaveLists
                                            .Where(x => x.EmployeeId == EMPLOYEEID && x.BranchId == BRANCHID && x.Status != UTILITY.LEAVECANCELLED)
                                            .Between(EmployeeLeaveList.FromDate, EmployeeLeaveList.ToDate)
                                            .Count() > 0;

                if (isPreviousLeaveExists)
                {
                    ViewData["Message"] = "You have already applied a leave within this date range. Please check.";
                    ViewData["IsLop"] = false;
                    return View("EmployeeRequestFrom", EmployeeLeaveList);
                }
                LeaveTransaction leavetransaction = dbCntx.LeaveTransactions
                        .Where(x => x.BranchId == BRANCHID && x.EmployeeId == EMPLOYEEID).OrderByDescending(x => x.CreatedOn)

HR.Web/Views/Leave/AppliedGrantLeaveStatus.cshtml
@model HR.Web.ViewModels.GrantLeaveListVm

@section Styles {
    <style type="text/css">
        .popover{
            max-width: 100%; 
            width: 500px;
        }
    </style>
}

@using (Html.BeginForm("ApproveLeave", "Leave", FormMethod.Post, new { id = "frmLeaveStatus", name = "frmLeaveStatus" }))
{
    <div class="page">
        <div class="panel panel-default panel-hovered panel-stacked mb10">
            <div class="box">
                <div class="box-body">
                    <div class="row">
                        <div class="form-group">
                            @Html.HiddenFor(x => x.EmployeeId)
                            @Html.HiddenFor(x => x.EmployeeLeaveID)
                            <div class="col-md-3">
                                <label class="control-label pull-right">Employee Name:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.Name</label>
                            </div>
                        </div>
                    </div>
                    <div class="row css10">
                        <div class="form-group">
                            <div class="col-md-3">
                                <label class="control-label pull-right">From Date:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.FromDate.ToString("MM/dd/yyyy")</label>
                            </div>                            
                        </div>
                    </div>
                    <div class="row css10">
                        <div class="form-group">
                            <div class="col-md-3">
                                <label class="control-label pull-right">To Date:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.ToDate.ToString("MM/dd/yyyy")</label>
                            </div>                            
                        </div>
                    </div>
                    <div class="row css10">
                        <div class="form-group">
                            <div class="col-md-3">
                                <label class="control-label pull-right">Reason:</label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label pull-left">@Model.Reason</label>
                            </div>
                        </div>
                    </div>   
                    @if (Model.Status == UTILITY.LEAVEPENDING)
                    {
                        <div class="row css10">
                            <div class="col-md-3"></div>
                            <div class="col-md-9">
                                <button class="btn btn-primary btn-sm"><i class="fa fa-check"></i>Approve</button>
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="popover" title="Remarks"><i class="fa fa-times"></i>Reject</button>
                            </div>                        
                        </div>
                    }
                    else if(Model.Status == UTILITY.LEAVEREJECTED)
                    {
                        <div class="row css10">
                            <div class="form-group">
                                <div class="col-md-3">
                                    <label class="control-label pull-right">Remarks:</label>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label pull-left">@Model.Remarks</label>
                                </div>
                            </div>
                        </div>
                    }
                    else if (Model.Status == UTILITY.LEAVEAPPROVED)
                    {
                        <div class="row css10">
                            <div class="form-group">
                                <div class="col-md-3">
                                    <label class="control-label pull-right">Status</label>
                                </div>
                                <div class="col-md-3">
                                    <label class="control-label pull-left">@UTILITY.LEAVEAPPROVED</label>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />

}


<div id="popover" class="hide">
    <div class="row">
        <div class="form-group">
            <div class="col-md-3">Remarks:</div>
            <div class="col-md-9">                    
                @Html.TextAreaFor(x => x.Remarks, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row css10">
        <div class="form-group">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <button type="button" class="btn btn-primary btn-sm" onclick="RejectLeave()"><i class="fa fa-floppy-o"></i>Save</button>
                <button type="button" class="btn btn-default btn-sm" onclick="Close()"><i class="fa fa-times"></i>Close</button>
            </div>                
        </div>
    </div>
</div>


@section Scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover({
            placement: 'right',
            html: true,
            content: function () {
                var anchorText = $(this).text();
                $('#popover').find('input[id=txtContent]').attr('value', anchorText);
                return $('#popover').html();
            },
           
            
        
        });
       
    });
   
            //}).blur(function () {
            //    $(this).popover('hide');
            //});
        
   
    function RejectLeave() {
        debugger;
        $('#frmLeaveStatus').attr('action', '@Url.Content("~/Leave/RejectLeave")')

        $('#frmLeaveStatus').submit();

    }
    function Close() {
    $('[data-toggle="popover"]').popover('hide')
        }
   
</script>
}

HR.Web/Views/Leave/EmployeeLeaveList.cshtml
@model IEnumerable<HR.Web.ViewModels.AppliedLeaveListVm>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<<div class="page">
    <div class="page-wrap">
        <div class="panel panel-default">
            <div class="panel-group" id="accordionDemo">
                <div class="panel panel-default ng-isolate-scope">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#collapse" data-toggle="collapse" class="accordion-toggle" data-parent="#accordionDemo"><b>Leave List</b></a>
                        </h4>
                    </div>
                    <div class="panel-collapse collapse in" id="collapse">
                        <div class="panel-body">
                            <div class="col-md-12">
                               
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>EmployeeId</th>
                                                <th>FromDate</th>
                                                <th>ToDate</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (var i = 0; i < Model.Count(); i++)
                                            {

                                                foreach (var item in Model.ElementAt(i).employeeLeaveList)
                                                {
                                                    <tr>
                                                        <td>@item.EmployeeId</td>
                                                        <td>@item.FromDate.ToString("MM/dd/yyyy")</td>
                                                        <td>@item.ToDate.ToString("MM/dd/yyyy")</td>
                                                        <td>Pending</td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        $(function () {

            $('#li_Leave').addClass('open');
            $('#li_appliedleavelist').addClass('active');
        });
    </script>
}

HR.Web/Views/Leave/GrantLeaveFormList.cshtml
@model HR.Web.ViewModels.HtmlTblVm<HR.Web.ViewModels.GrantLeaveListVm>

@section Styles {
    <style type="text/css">
        .popover {
            max-width: 100%;
            width: 500px;
        }
    </style>
}



<div class="page">
    <div class="page-wrap">
        <div class="row">
           
            @for (var i = 0; i < Model.TableData.Count; i++)
            {
                <div class="col-md-6">
                    <div class="panel panel-default panel-hovered panel-stacked mb10">
                        <div class="box">
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="control-label pull-left">From Date: <b>@Model.TableData[i].FromDate.ToShortDateString()</b></label>
                                    </div>
                                    <div class="col-md-6">
                                        <label class="control-label pull-right">To Date: <b>@Model.TableData[i].ToDate.ToShortDateString()</b></label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="control-label pull-left">Apply Date: <b>@Model.TableData[i].ApplyDate.ToShortDateString()</b></label>
                                    </div>
                                    <div class="col-md-6">
                                        @if (Model.TableData[i].Status == UTILITY.LEAVEAPPROVED)
                                        {
                                            <label class="control-label pull-right">Status: &nbsp;<span class="label label-success" style="font-weight:bold;font-size:14px;">@Model.TableData[i].Status</span></label>
                                        }
                                        else if (Model.TableData[i].Status == UTILITY.LEAVEREJECTED)
                                        {
                                            <label class="control-label pull-right">Status: &nbsp;<span class="label label-danger" style="font-weight:bold;font-size:14px;">@Model.TableData[i].Status</span></label>
                                        }
                                        else if (Model.TableData[i].Status == UTILITY.LEAVECANCELLED)
                                        {
                                            <label class="control-label pull-right">Status: &nbsp;<span class="label label-primary" style="font-weight:bold;font-size:14px;">@Model.TableData[i].Status</span></label>
                                        }
                                        else if (string.IsNullOrWhiteSpace(Model.TableData[i].Status))
                                        {
                                            <label class="control-label pull-right">Status:&nbsp;<span class="label label-info" style="font-weight:bold;font-size:14px;">Pending</span></label>
                                        }
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="control-label pull-left">Leave Type: <b>@Model.TableData[i].LeaveTypeDesc</b></label>
                                    </div>
                                    <div class="col-md-6">
                                        <label class="control-label pull-right">Total Days: <b>@Model.TableData[i].TotalDays.Value</b></label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <blockquote>
                                            <p>@Model.TableData[i].Reason</p>
                                            @if (!string.IsNullOrWhiteSpace(Model.TableData[i].Remarks))
                                            {
                                                <p>@Model.TableData[i].Remarks</p>
                                            }
                                            <div class="pull-right">
                                                <button class="btn btn-primary btn-sm"
                                                        type="button"
                                                        onclick="location.href = '@Url.Content("~/Leave/AppliedGrantLeaveStatus?EmployeeLeaveID=")'+ @Model.TableData[i].EmployeeLeaveID">
                                                    <i class="fa fa-eye"></i>&nbsp;View
                                                </button>
                                            </div>
                                        </blockquote>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="pagination" class="pull-right"></div>
            </div>
        </div>
    </div>
</div>


@*@using (Html.BeginForm("GrantLeaveFormList", "Leave", FormMethod.Post, new { id = "frmgrantleaveform", name = "frmgrantleaveform" }))
{
    <input type="hidden" id="employeeLeaveID" name="employeeLeaveID" />
    <input type="hidden" id="employeeRemarks" name="employeeRemarks" />
    <div id="popoverCancel" class="hide">
        <div class="row">
            <div class="form-group">
                <div class="col-md-3">Remarks:</div>
                <div class="col-md-9">

                    <textarea id="txtRemarks" name="txtRemarks" class="form-control"></textarea>
                </div>
            </div>
        </div>
        <div class="row css10">
            <div class="form-group">
                <div class="col-md-3">
                </div>
                <div class="col-md-9">
                    <button type="button" class="btn btn-primary btn-sm" onclick="CancelLeave()"><i class="fa fa-floppy-o"></i>Save</button>
                    <button type="button" class="btn btn-default btn-sm" onclick="ClosePopUp()"><i class="fa fa-times"></i>Close</button>
                </div>
            </div>
        </div>
    </div>
}*@
@section Scripts{
    <script src="~/Scripts/Core/jquery.bootpag.min.js"></script>
    <script type="text/javascript">
    //function OpenCancelPopover(empLeaveId){
    //    debugger;

    //    $('#popoverCancel').popover('show');
    //    //$('[data-toggle="popoverCancel"]').popover('show');
    //    $('#employeeLeaveID').val(empLeaveId);
    //}

    $(function () {
        $('#li_Leave').addClass('open');
        $('#li_grantleaveform').addClass('active');

        //$('[data-toggle="popoverCancel"]').popover({
        //    placement: 'left',
        //    html: true,
        //    content: function () {
        //        return $('#popoverCancel').html();
        //    }
        //});

        //$('[data-toggle="popoverCancel"]').popover({
        //    placement: 'top',
        //    html: true,
        //    content: function () {

        //        return $('#popoverCancel').html();
        //    }
        //})
        debugger;
        $('#pagination').bootpag({
            total: @Model.PageLength,
            page: @Model.CurrentPage,
            maxVisible: 6,
            href: '@Url.Content("~/Leave/GrantLeaveFormList?page="){{number}}', //"#pro-page-{{number}}",
            leaps: false,
            next: 'Next',
            prev: 'Prev',
            wrapClass: 'pagination pagination-sm'
        }).on('page', function (event, num) {
            $(".content3").html("Page " + num); // or some ajax content loading...
        });
    });

    //function cancelRequest(id) {
    //    $('#employeeLeaveID').val(id);
    //}

    //function CancelLeave() {
    //    var remarks = $('#txtRemarks').val();
    //    $('#employeeRemarks').val(remarks);
    //    $('#popoverCancel').find('textarea[id=txtRemarks]').attr('value', remarks);
    //    $('#frmCancelLeave').submit();

    //}
    //function ClosePopUp() {
    //    $('[data-toggle="popoverCancel"]').popover('hide');
    //}

    </script>
}